version: "3"
services:

    jeep:
        privileged: true
        build: .
        container_name: jeep
        tty: true
        cap_add:
            - ALL
        volumes:
            - "./:/opt/jeep:delegated"